// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCGXpNrKEC9K3hVe02OmrfYJasDHF5gB4',
    appId: '1:909477181676:web:9089ee02877b6f98120dc9',
    messagingSenderId: '909477181676',
    projectId: 'todowebapp-f175c',
    authDomain: 'todowebapp-f175c.firebaseapp.com',
    storageBucket: 'todowebapp-f175c.firebasestorage.app',
    measurementId: 'G-4QDXRJQCTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpD8hlj0LM-Fdjco_gnYa4VMplSRRPM3M',
    appId: '1:909477181676:android:2dfec32a65a01586120dc9',
    messagingSenderId: '909477181676',
    projectId: 'todowebapp-f175c',
    storageBucket: 'todowebapp-f175c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMwwtw2EDweD0QcGxxyIttABW9gWKSARE',
    appId: '1:909477181676:ios:e7947ea9a238d3fd120dc9',
    messagingSenderId: '909477181676',
    projectId: 'todowebapp-f175c',
    storageBucket: 'todowebapp-f175c.firebasestorage.app',
    iosBundleId: 'com.example.toDoWebApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMwwtw2EDweD0QcGxxyIttABW9gWKSARE',
    appId: '1:909477181676:ios:e7947ea9a238d3fd120dc9',
    messagingSenderId: '909477181676',
    projectId: 'todowebapp-f175c',
    storageBucket: 'todowebapp-f175c.firebasestorage.app',
    iosBundleId: 'com.example.toDoWebApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCGXpNrKEC9K3hVe02OmrfYJasDHF5gB4',
    appId: '1:909477181676:web:c36fc2f5c4d1b307120dc9',
    messagingSenderId: '909477181676',
    projectId: 'todowebapp-f175c',
    authDomain: 'todowebapp-f175c.firebaseapp.com',
    storageBucket: 'todowebapp-f175c.firebasestorage.app',
    measurementId: 'G-4K509QDYP8',
  );
}
